name: Boom Action JS
description: Automate Boom Token interactions, liquidity management, and analytics using GitHub Actions.
author: Boomtoknlab  

# GitHub Marketplace branding
branding:
  icon: zap
  color: orange

# Define your inputs
inputs:
  private-key:
    description: Private key for executing transactions securely
    required: true
  rpc-url:
    description: RPC URL API of the blockchain node
    required: true
  action-type:
    description: Type of action (transfer, stake, liquidity add/remove)
    required: false
    default: 'transfer'

# Define your outputs
outputs:
  transaction-hash:
    description: Hash of the executed transaction
  status:
    description: Success or failure status of the transaction

# Define how the action runs
runs:
  using: node20
  main: dist/index.js

# Add categories for better discoverability
categories:
  - automation
  - cryptocurrency
  - blockchain
